apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: beacon
  labels:
    app: beacon
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["serving.kserve.io/v1alpha1"]
    resources: ["llminferenceservices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
