apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beacon-data
  namespace: beacon
  labels:
    app: beacon
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
