apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: beacon
  namespace: beacon
  labels:
    app: beacon
spec:
  selector:
    matchLabels:
      app: beacon
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - beacon
